name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Bundle and Run Ruby scripts
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
        bundle exec ruby lib/3_1_using_ruby_graph_library.rb
        bundle exec ruby lib/3_2_plain_ruby.rb
